name: Profile Readme Development Stats

on:
  schedule:
    # Runs at 12am IST daily
    - cron: '30 18 * * *'
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Update Readme with Metrics
        uses: anmol098/waka-readme-stats@v4
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          # Optional flags
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
