name: Waka Readme Stats

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Runs daily at midnight UTC

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Required to update README
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4  # Updated from v2 to v4
        
      - name: Update Waka Stats
        uses: anmol098/waka-readme-stats@v4
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}  # Changed from GH_TOKEN to GITHUB_TOKEN
          
          # Optional settings (your selections are fine):
          SHOW_TITLE: true
          SHOW_TOTAL: true
          SHOW_LINES_OF_CODE: true
          SHOW_LANGUAGES: true
          TIME_RANGE: last_7_days
