name: Waka Readme Stats  # This MUST be the first line

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    
    steps:
      - uses: actions/checkout@v4
      - name: Update Waka Stats
        uses: anmol098/waka-readme-stats@v4
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          
          # Optional settings (your selections are fine):
          SHOW_TITLE: true
          SHOW_TOTAL: true
          SHOW_LINES_OF_CODE: true
          SHOW_LANGUAGES: true
          TIME_RANGE: last_7_days
